# MariaDBのpvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-storage
  local:
    path: /C/Users/inose.t/Pictures/NextCloud
  resources:
    requests:
      storage: 60Gi
